### ISSUE TITLE
getJob Unhanded error when data is undefined

### ISSUE THREAD

**Issue by lyntco** [gideonairex/disqueue-node#10]
When there are no jobs in the queue, `data` in `getJob` is undefined:

```
/Users/larlyn/projects/newlangs/disque/node_modules/disqueue-node/lib/commands-list/get-job.js:50
            for ( var i = 0; i < data.length; ++i ) {
                                     ^

TypeError: Cannot read property 'length' of null
    at null.callback (/Users/larlyn/projects/newlangs/disque/node_modules/disqueue-node/lib/commands-list/get-job.js:50:29)
    at DisqueClient.sendReply (/Users/larlyn/projects/newlangs/disque/node_modules/disqueue-node/lib/disqueue-client.js:210:17)
    at self.parser.execute (/Users/larlyn/projects/newlangs/disque/node_modules/disqueue-node/lib/disqueue-client.js:187:10)
    at Socket.<anonymous> (/Users/larlyn/projects/newlangs/disque/node_modules/disqueue-node/lib/disqueue-client.js:77:15)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

disque is version disque 1.0-rc1

**Comment by gideonairex** [comment]
I will look into this. Thanks @lyntco and have a fix.

**Comment by gideonairex** [comment]
Hi @lyntco. I didnt expect that the return would be null in disque 1.0-rc1 if there is an empty result. Anyways I added the checking for it. Thanks! here is the [commit](https://github.com/gideonairex/disqueue-node/commit/bc100a585a13ba54593309068fcf755d5c031689). I also added it in disqueue-node 1.2.3. Just close this if you have verified it.

**Comment by lyntco** [comment]
Thanks buddy, works like a charm! 😄

**Comment by gideonairex** [comment]
Youre welcome! ;)
